### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by felipemartins210** [Temtaime/aesir#2] opened 2018-02-15 11:55 UTC
![erro client](https://user-images.githubusercontent.com/8534899/36255472-535bf68c-1236-11e8-8954-ed4e852512cf.png)

I am using rathena.

**Comment by Temtaime** [comment] 2018-02-15 11:57
Use packetver 20170517 and disable packet obfuscation. Should work out of the box with latest rathena.

**Comment by felipemartins210** [comment] 2018-02-15 21:00
**_I did, but now is happening it._**

![erro client](https://user-images.githubusercontent.com/8534899/36280681-3a00ea84-1282-11e8-9203-2ab6271f9159.png)

**Comment by Temtaime** [comment] 2018-02-16 09:39
Make sure that other processes are not using grf files in time when you run the client.

**Comment by felipemartins210** [comment] 2018-02-16 18:10
I am sure, I reboot my pc and it stills happening it.

**Comment by felipemartins210** [comment] 2018-02-16 21:29
is it work with rathena right?

**Comment by Temtaime** [comment] 2018-02-17 11:24
Yes, but the error is not related to the server.
Maybe you run some antivirus software ?
Try to disable it, don't know how it could interact, but anyway.

**Comment by luan122** [comment] 2018-02-21 20:13
@felipemartins210 if you use Itau, BB, Caixa economicas as your banks, you need to uninstall their protection, since gas block alot of files that are related to RO

**Comment by felipemartins210** [comment] 2018-02-21 20:46
nothing! i give up T_T

**Comment by edddieee** [comment] 2020-01-10 17:40
Just for future reference.
I had the same problem when I tried to use an updated GRF, but using a kRO client from 2017 it works properly.

NOTE: The problem will happen if u tried to use an encrypted GRF.

**Comment by Temtaime** [comment] 2021-01-20 21:19
The issue is outdated, so i think it's time to close it.
If there're new problems, feel free to create a new issue.
There'll new release in near future with many fixes.

**Closed as completed by Temtaime** 2021-01-20 21:19 UTC
